# Generated by Django 2.0 on 2017-12-04 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Savings'), ('C', 'Credit'), ('D', 'Debit'), ('I', 'Investment')], max_length=1)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_date', models.DateField(null=True)),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('reference_number', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='refinance.Account')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='refinance.Category')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refinance.Bank'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('refinance.transaction',),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('refinance.transaction',),
        ),
    ]
